project_id = "gomoku-lite"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["http://127.0.0.1:5173/auth/callback"]

[auth.email]
enable_signup = false

[auth.external.discord]
enabled = true
client_id = "env(SUPABASE_AUTH_DISCORD_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_DISCORD_SECRET)"
redirect_uri = "http://127.0.0.1:54321/auth/v1/callback"

[realtime]
enabled = true
